linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gocritic
    - exhaustive
  disable-all: true

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
